openapi: 3.0.0
info:
  title: "MTG Search Engine"
  description: "Search for MTG cards, see https://monarch.djpiper28.co.uk, or https://github.com/squiretournamentservices/mtg-search-engine"
  version: 1.0.0

servers:
  - url: "https://monarch.djpiper28.co.uk/api"
    description: "Hosted version (very soft rate limits)"
  - url: "https://localhost:4365"
    description: "Localhost, use docker-compose"

paths:
  "/api":
    post:
      summary: "Query magic cards!"
      description: "This is probably the main API that you care about"
      responses:
        "400":
          description: "The request has no body"
          content:
            application/text:
              schema:
                type: string
        "500":
          description: "The query is not valid"
          content:
            application/text:
              schema:
                type: string
        "200":
          description: "The query is not valid"
          content:
            application/json:
              schema:
                type: object
                properties:
                  page_size:
                    type: number
                  page:
                    type: number
                  cards_total:
                    type: number
                  cards:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        mana_cost:
                          type: string
                        oracle_text:
                          type: string
                        types:
                          type: array
                          items:
                            type: string
                        power:
                          type: number
                        toughness:
                          type: number
                        cmc:
                          type: number
                        colours:
                          description: "A WUBRG field array (0x11111) is WUBRG, 0x10000 is W, ..."
                          type: number
                        color_identity:
                          description: "A WUBRG field array (0x11111) is WUBRG, 0x10000 is W, ..."
                          type: number
                        sets:
                          type: array
                          items:
                            type: string
