name: "Frontend"

on:
  push:
    branches: [ "*" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]

jobs:
  configure:
    name: Configure
    runs-on: ubuntu-22.04
    outputs:
      tag: ${{steps.configure.outputs.tag}}
      sha: ${{steps.configure.outputs.sha}}
      upload_url: ${{steps.create_release.outputs.upload_url}}

    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.12.0
        with:
          access_token: ${{github.token}} # needs other token https://github.com/styfle/cancel-workflow-action/issues/7

      - name: Checkout
        if: steps.configure.outputs.tag != null
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: build_frontend 
        id: build_frontend 
        shell: bash
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends npm
          pwd
          ls
          cd frontend/
          npm i
          npm run build
